{
  "id": "BIT-gitlab-2021-22189",
  "details": "Starting with version 13.7 the Gitlab CE/EE editions were affected by a security issue related to the validation of the certificates for the Fortinet OTP that could result in authentication issues.",
  "aliases": [
    "CVE-2021-22189"
  ],
  "modified": "2025-02-26T16:37:33.026Z",
  "published": "2024-03-06T11:20:18.492Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*"
    ],
    "severity": "High"
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22189.json"
    },
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/296557"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "gitlab",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/gitlab"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "13.6.0"
            },
            {
              "fixed": "13.6.7"
            },
            {
              "introduced": "13.7.0"
            },
            {
              "fixed": "13.7.7"
            },
            {
              "introduced": "13.8.0"
            },
            {
              "fixed": "13.8.4"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2021-22189.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}