{
  "id": "BIT-pip-2021-3572",
  "details": "A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.",
  "aliases": [
    "CVE-2021-3572",
    "GHSA-5xp3-jfq3-5q8x",
    "PYSEC-2021-437"
  ],
  "modified": "2024-06-23T19:56:34.118Z",
  "published": "2024-03-06T11:01:55.978Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:pypa:pip:*:*:*:*:*:*:*:*"
    ],
    "severity": "Medium"
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1962856"
    },
    {
      "type": "WEB",
      "url": "https://www.oracle.com/security-alerts/cpuapr2022.html"
    },
    {
      "type": "WEB",
      "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20240621-0006/"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "pip",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/pip"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "21.1.0"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/pip/BIT-pip-2021-3572.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}