{
  "id": "BIT-gitlab-2024-2818",
  "details": "An issue has been discovered in GitLab CE/EE affecting all versions before 16.8.5, all versions starting from 16.9 before 16.9.3, all versions starting from 16.10 before 16.10.1. It was possible for an attacker to cause a denial of service using malicious crafted description parameter for labels.",
  "aliases": [
    "CVE-2024-2818"
  ],
  "modified": "2024-11-05T07:36:31.248Z",
  "published": "2024-04-03T10:50:50.059Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:community:*:*",
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:enterprise:*:*",
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*",
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*"
    ],
    "severity": "Medium"
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/434803"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "gitlab",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/gitlab"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "16.8.5"
            },
            {
              "introduced": "16.9.0"
            },
            {
              "fixed": "16.9.3"
            },
            {
              "introduced": "16.10.0"
            },
            {
              "fixed": "16.10.1"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/gitlab/BIT-gitlab-2024-2818.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}