{
  "id": "BIT-sqlite-2021-31239",
  "details": "An issue found in SQLite SQLite3 v.3.35.4 that allows a remote attacker to cause a denial of service via the appendvfs.c function.",
  "aliases": [
    "CVE-2021-31239"
  ],
  "modified": "2024-03-06T11:25:28.861Z",
  "published": "2024-03-06T11:06:35.104Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:sqlite:sqlite:3.35.4:*:*:*:*:*:*:*"
    ],
    "severity": "High"
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/Tsiming/Vulnerabilities/blob/main/SQLite/CVE-2021-31239"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/73XUIHJ6UT75VFPDPLJOXJON7MVIKVZI/"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FXFL4TDAH72PRCPD5UPZMJMKIMVOPLTI/"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/202311-03"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20230609-0010/"
    },
    {
      "type": "WEB",
      "url": "https://www.sqlite.org/cves.html"
    },
    {
      "type": "WEB",
      "url": "https://www.sqlite.org/forum/forumpost/d9fce1a89b"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "sqlite",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/sqlite"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.35.4"
            },
            {
              "last_affected": "3.35.4"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/sqlite/BIT-sqlite-2021-31239.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}