{
  "id": "BIT-tensorflow-2023-25671",
  "details": "TensorFlow is an open source platform for machine learning. There is out-of-bounds access due to mismatched integer type sizes. A fix is included in TensorFlow version 2.12.0 and version 2.11.1.",
  "aliases": [
    "CVE-2023-25671",
    "GHSA-j5w9-hmfh-4cr6"
  ],
  "modified": "2024-03-06T11:25:28.861Z",
  "published": "2024-03-06T11:08:02.488Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*"
    ],
    "severity": "High"
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/tensorflow/tensorflow/commit/2eedc8f676d2c3b8be9492e547b2bc814c10b367"
    },
    {
      "type": "WEB",
      "url": "https://github.com/tensorflow/tensorflow/commit/760322a71ac9033e122ef1f4b1c62813021e5938"
    },
    {
      "type": "WEB",
      "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-j5w9-hmfh-4cr6"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "tensorflow",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/tensorflow"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.12.0"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/tensorflow/BIT-tensorflow-2023-25671.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}